FROM arm32v7/node:8.11.4-stretch

# crafted and tuned by pierre@ozoux.net and sing.li@rocket.chat
MAINTAINER buildmaster@rocket.chat

RUN groupadd -r rocketchat \
&&  useradd -r -g rocketchat rocketchat \
&&  mkdir -p /app/uploads \
&&  chown rocketchat.rocketchat /app/uploads

VOLUME /app/uploads

# gpg: key 4FD08014: public key "Rocket.Chat Buildmaster <buildmaster@rocket.chat>" imported
RUN gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 0E163286C20D07B9787EBE9FD7F9D0414FD08104

ENV RC_VERSION 0.74.3

WORKDIR /app

RUN apt-get update && apt-get -y install g++ build-essential
RUN apt-get update && apt-get -y upgrade
RUN apt-get install libstdc++6
RUN apt-get -y install python
RUN curl -fSL "https://releases.rocket.chat/${RC_VERSION}/download" -o rocket.chat.tgz \
&&  curl -fSL "https://releases.rocket.chat/${RC_VERSION}/asc" -o rocket.chat.tgz.asc \
&&  gpg --batch --verify rocket.chat.tgz.asc rocket.chat.tgz \
&&  tar zxvf rocket.chat.tgz \
&&  rm rocket.chat.tgz rocket.chat.tgz.asc

RUN cd bundle/programs/server  \
&& apt-get -y install libstdc++6 \
&& rm -rf npm/node_modules/meteor/emojione_emojione/node_modules/grunt-contrib-qunit \
&& rm -rf npm/node_modules/sharp/vendor \
&& export NODE_ENV=production \
&& npm i --unsafe-perm

# Start hack for sharp...
RUN cd /app/bundle/programs/server \
&& apt-get -y install execstack \
&& execstack --clear-execstack npm/node_modules/sharp/vendor/lib/librsvg-2.so* \
&& rm -rf npm/node_modules/meteor/konecty_user-presence/node_modules/colors/lib/.colors.js.swp

# End hack for sharp

USER rocketchat

WORKDIR /app/bundle

# needs a mongoinstance - defaults to container linking with alias 'db'
ENV DEPLOY_METHOD=docker-armhf-raspberrypi \
    NODE_EVN=production \
    MONGO_URL=mongodb://mongo:27017/rocketchat \
    MONGO_OPLOG_URL=mongodb://mongo:27017/local \
    HOME=/tmp \
    PORT=3000 \
    ROOT_URL=http://localhost:3000 \
    Accounts_AvatarStorePath=/app/uploads

EXPOSE 3000

CMD ["node", "main.js"]
