FROM balenalib/rpi-raspbian
# Original MAINTAINER Chip Dickson <cdickson@sumglobal.com> - Mongo 3.2 for RPI

RUN apt-get update && apt-get upgrade -y   \
  && apt-get -y install wget 
#    apt-get -y install binutils && \
#    apt-get install libssl1.0.0 libssl-dev -y
# This copies contents of dir mongo3-2 to /usr/bin
RUN wget --backups=0 "https://github.com/SUMGlobal/rpi-mongodb/raw/master/mongo3-2/mongo" \ 
&& wget --backups=0 "https://github.com/SUMGlobal/rpi-mongodb/raw/master/mongo3-2/mongod"  \ 
&& wget --backups=0 "https://github.com/SUMGlobal/rpi-mongodb/raw/master/mongo3-2/mongos" \
&& mv mongo /usr/bin \
&& mv mongod /usr/bin \
&& mv mongos /usr/bin

RUN adduser --ingroup nogroup --shell /etc/false --disabled-password --gecos "" --no-create-home mongodb \
    && chown root:root /usr/bin/mongo* \
    && chmod 755 /usr/bin/mongo* \
    && mkdir -p /var/log/mongodb \
    && chown mongodb:nogroup /var/log/mongodb \
    && mkdir -p /var/lib/mongodb \
    && chown mongodb:root /var/lib/mongodb \
    && chmod 775 /var/lib/mongodb \
    && mkdir -p /data/db \
    && rm -Rf /tmp/*

# This copies contents of dir config to /root
COPY config /root
RUN mv /root/mongodb.conf /etc/mongodb.conf \
    && mv /root/mongodb.service /lib/systemd/system/mongodb.service \
    && chmod 755 /root/run.sh

VOLUME ["/data"]

EXPOSE 27017

CMD ["/root/run.sh"]

